// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGVwlLeTSLdleG3JA64AWnJWTuNoOPSg',
    appId: '1:511274380247:web:ba3df4b4a39da3b69a7992',
    messagingSenderId: '511274380247',
    projectId: 'wasure-mobile',
    authDomain: 'wasure-mobile.firebaseapp.com',
    storageBucket: 'wasure-mobile.appspot.com',
    measurementId: 'G-VPLGVXGL5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyJcXJ3bCAZIxVfX1I1pU8nD8-oWZ61I',
    appId: '1:511274380247:android:aab7fce01fa6f9b39a7992',
    messagingSenderId: '511274380247',
    projectId: 'wasure-mobile',
    storageBucket: 'wasure-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClV6ld7KeuTvo6dwQthpDST5CVVB3nbn0',
    appId: '1:511274380247:ios:992c1ed6312702429a7992',
    messagingSenderId: '511274380247',
    projectId: 'wasure-mobile',
    storageBucket: 'wasure-mobile.appspot.com',
    iosBundleId: 'com.example.wasureMobaileFutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClV6ld7KeuTvo6dwQthpDST5CVVB3nbn0',
    appId: '1:511274380247:ios:992c1ed6312702429a7992',
    messagingSenderId: '511274380247',
    projectId: 'wasure-mobile',
    storageBucket: 'wasure-mobile.appspot.com',
    iosBundleId: 'com.example.wasureMobaileFutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGVwlLeTSLdleG3JA64AWnJWTuNoOPSg',
    appId: '1:511274380247:web:b07b53b3f90df27e9a7992',
    messagingSenderId: '511274380247',
    projectId: 'wasure-mobile',
    authDomain: 'wasure-mobile.firebaseapp.com',
    storageBucket: 'wasure-mobile.appspot.com',
    measurementId: 'G-ENBC614YL5',
  );
}
